In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib as plt 
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification

In [3]:
#now we will create the dataset
X,Y =make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [4]:

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=42)


In [5]:
#modelTraining
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [6]:
model.fit(X_train,Y_train)

LogisticRegression()

In [7]:
Y_pred = model.predict (X_test)

In [8]:
print (Y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]


In [9]:
#Probability Ki konsa h koi bich m ajata h to uske liye hota h is case me jurrt nhi h hme
model.predict_proba(X_test)


array([[7.74481865e-01, 2.25518135e-01],
       [3.36701953e-02, 9.66329805e-01],
       [6.70684311e-01, 3.29315689e-01],
       [7.98688284e-02, 9.20131172e-01],
       [9.76617515e-01, 2.33824847e-02],
       [4.13590037e-02, 9.58640996e-01],
       [9.79029806e-01, 2.09701936e-02],
       [9.59367633e-01, 4.06323668e-02],
       [8.08516510e-01, 1.91483490e-01],
       [6.84961496e-01, 3.15038504e-01],
       [9.13670314e-01, 8.63296857e-02],
       [2.63599422e-01, 7.36400578e-01],
       [5.25846966e-01, 4.74153034e-01],
       [2.11919907e-01, 7.88080093e-01],
       [7.93598597e-01, 2.06401403e-01],
       [9.46623760e-01, 5.33762402e-02],
       [2.62972095e-02, 9.73702790e-01],
       [3.24226362e-01, 6.75773638e-01],
       [3.14809449e-01, 6.85190551e-01],
       [2.04954712e-01, 7.95045288e-01],
       [5.04587814e-01, 4.95412186e-01],
       [9.66703959e-01, 3.32960407e-02],
       [2.00518184e-01, 7.99481816e-01],
       [7.77899761e-01, 2.22100239e-01],
       [8.729913

In [118]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [142]:
score = accuracy_score(Y_test,Y_pred)
cm = confusion_matrix(Y_test,Y_pred)
report = classification_report(Y_test,Y_pred)
print (score)
print(cm)
print(report)

0.8466666666666667
[[118  17]
 [ 29 136]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



In [12]:
#now we will do HYperparamerter Tuning ,cv & grid

In [122]:
model1 =LogisticRegression()#(penalty='elasticnet', l1_ratio=0.5, solver='saga', max_iter=2000)
 # You can increase the value if needed

penalty =['l1','l2','elasticnet']#The penalty specifies the type of regularization
#that is applied to the model to prevent overfitting LAsso.Ridge,Elasticnet

c_values = [100,10,1.0,0.1,0.01]#The C parameter controls the regularization strength, 
#where C is the inverse of the regularization strength. Smaller values of C mean stronger regularization

solver = ['newton-cg','lbfgs','liblinear','sag','saga']#Solvers are optimization algorithms 
#used to minimize the loss function and find the best coefficients for the logistic regression model

we r creating a dictionary named params that will hold the different hyperparameters we want to test in your logistic regression model. Here's a breakdown:

In [124]:
params =dict(penalty=penalty,C=c_values,solver=solver)
# Create parameter grid with correct solver-penalty pairs
# params = [
#     {'penalty': ['l2'], 'C': c_values, 'solver': ['newton-cg', 'lbfgs', 'sag']},
#     {'penalty': ['l1'], 'C': c_values, 'solver': ['liblinear']},
#     {'penalty': ['l2', 'l1', 'elasticnet'], 'C': c_values, 'solver': ['saga'], 'l1_ratio': [0.5, 0.7]}  # l1_ratio is needed for elasticnet
# ]


#grid Search cv(we will find the best parameter that will be fit for our dataset)

In [126]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [128]:
#gridserch cv
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model1,param_grid=params,
                  scoring='accuracy',cv=cv,n_jobs=-1)
# from sklearn.model_selection import GridSearchCV

# # Assuming model1 is your initialized model and params is your parameter grid
# grid = GridSearchCV(estimator=model1, 
#                     param_grid=params, 
#                     scoring='accuracy',   # Change this if you're using another metric
#                     cv=cv,                # StratifiedKFold or another cross-validation strategy
#                     n_jobs=-1)            # Parallel processing


In [130]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [132]:
grid.fit(X_train,Y_train)

/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [134]:
grid.best_params_#this means the paramtwre which can be used for hyperparameter tuning
#based on the accuracy score

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [136]:
#provides the best cross-validated score achieved during the 
#search over the specified parameter grid.

grid.best_score_

0.8785714285714287

In [144]:
Y_pred= grid.predict(X_test)

In [146]:
score = accuracy_score(Y_test,Y_pred)
cm = confusion_matrix(Y_test,Y_pred)
report = classification_report(Y_test,Y_pred)
print (score)
print(cm)
print(report)

0.8533333333333334
[[124  11]
 [ 33 132]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



##Randamised Serch CV

In [150]:
##Randamised Serch CV
from sklearn.model_selection import RandomizedSearchCV

In [160]:
model = LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5,scoring = 'accuracy')

In [162]:
randomcv.fit(X_train,Y_train)

/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logist

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [164]:
randomcv.best_score_

0.8785714285714287

In [172]:
randomcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.01}

In [192]:
y_pred= randomcv.predict(X_test)

In [194]:
score = accuracy_score(Y_test,y_pred)
cm = confusion_matrix(Y_test,y_pred)
report = classification_report(Y_test,y_pred)
print (score)
print(cm)
print(report)

0.8533333333333334
[[124  11]
 [ 33 132]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



In [ ]:
#major advt. is if we have large dataset it will take less time cz take samples